import{S as u,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const m="46153478-1b8179550e9312780d25c3b1d";async function f(n){const o=`https://pixabay.com/api/?key=${m}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`,r=await fetch(o);if(!r.ok)throw new Error("Failed to fetch images");return(await r.json()).hits}function g(n){const o=document.getElementById("gallery"),r=n.map(({webformatURL:e,largeImageURL:t,tags:s,likes:c,views:d})=>`
      <a href="${t}" class="gallery-item">
        <img src="${e}" alt="${s}" />
        <div class="info">
          <p>Likes: ${c}</p>
          <p>Views: ${d}</p>
        </div>
      </a>`).join("");o.innerHTML=r,new u(".gallery-item",{captionsData:"alt",captionDelay:250}).refresh(),console.log("renderGallery function called")}function y(){const n=document.getElementById("gallery");n.innerHTML="",console.log("clearGallery function called")}const h=document.getElementById("search-form");document.getElementById("gallery");const l=document.getElementById("loader");h.addEventListener("submit",async n=>{n.preventDefault();const o=document.getElementById("search-query").value.trim();if(!o){a.error({title:"Error",message:"Please enter a search term!"});return}y(),p();try{const r=await f(o);r.length===0?a.error({title:"Error",message:"No images found for this query!"}):(g(r),a.success({title:"Success",message:`Found ${r.length} images!`}))}catch{a.error({title:"Error",message:"Something went wrong. Try again later."})}finally{L()}});function p(){l.classList.remove("hidden")}function L(){l.classList.add("hidden")}
//# sourceMappingURL=index.js.map
